#!/bin/bash

case $1 in 
    restart )
        killall supervise.agollo_server agollo_server
        sleep 1
        nohup ./supervise.agollo_server ./ >/tmp/nohup_agollo.log  2>&1 &
        ;;
    start )
        num=`ps axfu | grep agollo_server | grep -v grep | wc -l`
        if [ $num -ge 1 ]; then
            echo "agollo_server or supervice has started"
            exit 0
        fi
        nohup ./supervise.agollo_server ./ >/tmp/nohup_agollo.log 2>&1 &
        ;;
    stop )
        killall supervise.agollo_server agollo_server
        ;;
    * ) 
        echo "start | stop | restart"
        ;;
esac

