[dmp]
cluster = [ "as_ali_vg", "as_aws_vg", "as_aws_sg", "as_aws_fk", "as_aws_se", "dsp_ali_vg", "dsp_hw_hk", "dsp_ali_cn",]
[dmp.namespace]
application = [ "config/dmp-server/bes_media_rta", "config/dmp-server/logic_audiences", "config/dmp-server/package_tags", "config/dmp-server/pkg_dict", "config/dmp-server/server_v2", "config/dmp-server/tencent_ad_rta"]
