portaddr="http://apollo-config.mobvista.com"
env="DEV"
timeout=60
dsp_ali_vg="http://vg-consul-dsp.mobvista.com:8500"
dsp_ali_cn="http://cn-consul-dsp.mobvista.com:8500"
dsp_hw_hk="http://hk-consul-dsp.mobvista.com:8500"
m_ali_vg="http://vg-consul-ali.mobvista.com:8500"
m_aws_se="http://se-consul.mobvista.com:8500"
m_aws_sg="http://sg-consul.mobvista.com:8500"
m_aws_fk="http://fk-consul.mobvista.com:8500"
m_aws_vg="http://vg-consul.mobvista.com:8500"
[usermap.apollo]
token="0bcbd744e2c08203a384a740f5aa9ab13f7cc24c"
[usermap.dsp]
token="6f27190ea9ff6dd9f3819a2df069a3546bcc0928"
[usermap.pioneer]
token="ade2f9d8590139607b3fb4847c0d1224d3834366"
[usermap.bidforce]
token="82e0cb400cac759b452f00a9b0c72191c42030b7"
[usermap.m_abtest]
token="c55b6d4dedc70b574efff2db18a4fac792f88fb9"
[usermap.dsp_abtest]
token="34aed23105b9b467b0fc40f0fdc0eb2b20a4c240"

