ipport = "localhost:18080"
[cluster_info]
	[cluster_info.dsp_ali_cn] 
	  consul_addr = "cn-consul-dsp.mobvista.com:8500"
	[cluster_info.dsp_ali_vg]
	  consul_addr = "vg-consul-dsp.mobvista.com:8500"
	[cluster_info.dsp_ali_hk]
	  consul_addr = "hk-consul-dsp.mobvista.com:8500"
	[cluster_info.m_ali_vg]
	  consul_addr = "vg-consul-ali.mobvista.com:8500"
	[cluster_info.m_aws_se] 
	  consul_addr = "se-consul.mobvista.com:8500"
	[cluster_info.m_aws_sg]
	  consul_addr = "sg-consul.mobvista.com:8500"	
	[cluster_info.m_aws_fk] 
	  consul_addr = "fk-consul.mobvista.com:8500"	
	[cluster_info.m_aws_vg]
	  consul_addr = "vg-consul.mobvista.com:8500"
[appId_cluster_map]
dsp = [dsp_ali_cn, dsp_ali_vg,dsp_ali_hk]
