#white指白名单,black指黑名单
[[mappingrules]]
[mappingrules.dmp]
white = [ "dmp",]

[[mappingrules]]
[mappingrules.juno]
white = [ "juno",]

[[mappingrules]]
[mappingrules.nowin]
white = [ "nowin",]

[[mappingrules]]
[mappingrules.rtdsp]
white = [ "rtdsp", "dsp-retarget", "rtrs", "RTRS",]

[[mappingrules]]
[mappingrules.drs]
white = [ "drs",]

[[mappingrules]]
[mappingrules.dsp]
white = []